# Generated by Django 5.0 on 2024-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_APP', '0008_alter_subject_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
